services:

  tempo:
    image: grafana/tempo:latest
    container_name: ecommerce-tempo
    command:
      - "-config.file=/etc/tempo.yml"
    volumes:
      - ./tempo.yml:/etc/tempo.yml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"
    networks:
      - observability

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: ecommerce-otel-collector
    command:
      - "--config=/etc/otelcol-contrib/config.yaml"
    volumes:
      - ./otel-collector.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    depends_on:
      - tempo
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: ecommerce-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - tempo
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    container_name: ecommerce-prometheus
    command:
        - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus-data:/prometheus
    ports:
        - "9090:9090"
    depends_on:
        - otel-collector
    networks:
            - observability

networks:
  observability:
    name: ecommerce-observability
volumes:
  tempo-data:
  grafana-data:
  prometheus-data: